name: 'wh_demo'
version: '1.0.0'
config-version: 2
profile: 'wh_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  wh_demo:
    +materialized: view
    ods:
      +materialized: view
    dwd:
      +materialized: table
    dws:
      +materialized: table
    ads:
      +materialized: table
